# Database Configuration
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auth
    username: root
    password: 37824291
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDBDialect